FROM docker.m.daocloud.io/library/golang:1.26-bookworm
RUN apt-get update && apt-get install -y --no-install-recommends libsqlite3-dev build-essential git curl && rm -rf /var/lib/apt/lists/*
ENV GOPROXY=https://goproxy.cn,direct
